### ISSUE TITLE
Gallery page: Gallery albums aren't styled properly

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Zenith-Low-Loaders#18]
![gallery page01](https://cloud.githubusercontent.com/assets/13309730/8672672/4882a4a4-2a4e-11e5-82ea-28624b654013.png)

**Comment by arielcebudigital** [comment]
here is the knowledge base url for gallery
https://knowledgebase.titanweb.com.au/implementation-practices/nggallery-implementation-practices/gallery-layout-and-styles.
