### ISSUE TITLE
Banner section: Banner caption is overlapping banner

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Zenith-Low-Loaders#19]
Devices:  I pad and I pad mini

![img_0106](https://cloud.githubusercontent.com/assets/13309730/8673850/9bba12ac-2a57-11e5-994c-c8f6640b36de.PNG)

![l](https://cloud.githubusercontent.com/assets/13309730/8673995/a2419342-2a58-11e5-832f-1e39b644de65.PNG)

**Comment by arielcebudigital** [comment]
Base on the design PSD, it's already overlap :-)
