### ISSUE TITLE
Header section :Google map link is not navigating

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Zenith-Low-Loaders#22]
Browsers : Mozilla39, Opera 30, Chrome43, IE9

![header_section_2](https://cloud.githubusercontent.com/assets/13309806/8693044/b807eaac-2a88-11e5-86e8-2bee027d5f36.png)

**Comment by bernardtitan** [comment]
Ravi,
Don't make tickets like these. They can't be deleted.
