### ISSUE TITLE
Banner section :Banner images are not navigating when place the cursor on that image.

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Zenith-Low-Loaders#25]
Browsers : Mozilla39, Opera 30, Chrome43, IE9

![banner_section_2](https://cloud.githubusercontent.com/assets/13309806/8693100/391ce9b2-2a89-11e5-9cf4-15763a8e138c.png)

**Comment by arielcebudigital** [comment]
It's the behavior of the slick carousel. :-)
