### ISSUE TITLE
Banner section : Banner caption is overlapping on banner at resolutions 480,640 and 1024.

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Zenith-Low-Loaders#26]
Browser : Mozilla39

![banner_section_3](https://cloud.githubusercontent.com/assets/13309806/8693124/6d5bcd92-2a89-11e5-9022-cea788439212.png)

**Comment by arielcebudigital** [comment]
Base on the design PSD, it actually overlap.
