### ISSUE TITLE
Footer Section : Active state is not working for Privacy policy, Contact Us and Site Map

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Zenith-Low-Loaders#31]
Browsers : Mozilla39, Opera 30, Chrome43, IE9

![footer_01](https://cloud.githubusercontent.com/assets/13309806/8693304/0dc6ea18-2a8b-11e5-95d7-7f49a1fcf56f.png)

**Comment by arielcebudigital** [comment]
This is not a bug, there is no active state in the PSD for  footer menu, and also i think it's an enhancement
