### ISSUE TITLE
Our Fleet page : Unnecessary gap is occurring.

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Zenith-Low-Loaders#34]
Browsers : Mozilla39, Opera 30, Chrome43, IE9

![our-fleet_low-loader_2](https://cloud.githubusercontent.com/assets/13309806/8693465/2e4a37d0-2a8c-11e5-997a-a4e643148958.png)

![our-fleet_low-loader_3](https://cloud.githubusercontent.com/assets/13309806/8693469/35ec8af6-2a8c-11e5-99a4-a8a07821468d.png)

**Comment by ramoncebudigital** [comment]
Spacing is generated by Wysywyg Editor at the backend.
![screenshot_1](https://cloud.githubusercontent.com/assets/11186436/8844557/f05dc02c-3148-11e5-97c2-6093f727ebe9.png)
