### ISSUE TITLE
Testimonials page : Unnecessary gap is occurring and its applicable for news page also

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Zenith-Low-Loaders#41]
Browsers : Mozilla39, Opera 30, Chrome43, IE9

![testimonials_page_1](https://cloud.githubusercontent.com/assets/13309806/8694696/82c7f672-2a95-11e5-917b-afb5ab3ca714.png)

![testimonials_page_2](https://cloud.githubusercontent.com/assets/13309806/8694699/8845112a-2a95-11e5-8088-11d2f8f1a6cc.png)

**Comment by ramoncebudigital** [comment]
Please refer to this bug https://github.com/titan-cebu/Zenith-Low-Loaders/issues/34
