### ISSUE TITLE
Page Content: List items are not styled properly.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Zenith-Low-Loaders#61]
![page contentlists01](https://cloud.githubusercontent.com/assets/13309730/8716148/a5745f1a-2baa-11e5-9273-579c574882f9.png)

**Comment by ramoncebudigital** [comment]
working on my end.
![screenshot_3](https://cloud.githubusercontent.com/assets/11186436/8847195/02eb4d66-315f-11e5-9dbd-a5ada4c9c218.png)
